rest-producer:
  base-uri: http://rest-producer:9091
  hello-world-path: /hello


soap-producer:
  base-uri: http://soap-producer:9092
  hello-world-path: /ws


html-producer:
  base-uri: http://html-producer:9093


camel:
  netty:
    url: http://localhost
    port: 9090
    rest-hello-path: "rest/hello-world"
    soap-hello-path: "soap/hello-world"

